import type { DatasetManifest, LessonManifest } from "../content/manifest";
import { directives, executableSource, serializeNotebook, type NotebookCell } from "../notebook/format";
import { createZip } from "./zip";

export const LESSON_DATA_LOCK_SCHEMA = "https://studio.lang.bio/schemas/lesson-data-lock-v1.schema.json";

export type LessonDataLock = {
  $schema: typeof LESSON_DATA_LOCK_SCHEMA;
  schema: 1;
  kind: "biolang-lesson-data-lock";
  generatedAt: string;
  project: { notebook: string; script: string };
  lesson?: {
    id: string;
    title: string;
    version?: string;
    manifestUrl?: string;
    manifestSha256?: string;
    source: LessonManifest["source"];
  };
  files: Array<DatasetManifest & { role: "input" }>;
};

export type LessonProjectInput = {
  filename: string;
  workspaceName: string;
  cells: NotebookCell[];
  lesson?: LessonManifest | null;
  lessonVersion?: string;
  lessonManifestUrl?: string;
  lessonManifestSha256?: string;
  generatedAt?: string;
};

export function safeProjectBase(filename: string) {
  return filename.replace(/\.(bln|bl\.md|md|bl)$/i, "").replace(/[^a-z0-9._-]+/gi, "-").replace(/^-|-$/g, "") || "biolang-lesson";
}

export function generatedBioLangScript(cells: NotebookCell[], sourceNotebook: string) {
  const runnable = cells
    .map((cell, index) => ({ cell, index }))
    .filter(({ cell }) => cell.type === "code" && !directives(cell.source).skip)
    .map(({ cell, index }) => {
      const source = executableSource(cell.source);
      return source ? `# Notebook code cell ${index + 1}\n${source}` : "";
    })
    .filter(Boolean);
  const header = [
    "# Generated by BioLang Studio from a literate notebook.",
    `# Source notebook: ${sourceNotebook}`,
    "# Dataset bytes are not embedded; use Studio's CLI project export for verified preparation.",
    "# Lines marked # @skip in the notebook are intentionally omitted.",
  ];
  return `${header.join("\n")}\n\n${runnable.join("\n\n")}\n`;
}

export function lessonDataLock(input: LessonProjectInput): LessonDataLock {
  const base = safeProjectBase(input.filename);
  const notebook = `${base}.bln`;
  const script = `${base}.bl`;
  const lesson = input.lesson ? {
    id: input.lesson.id,
    title: input.lesson.title,
    ...(input.lessonVersion ? { version: input.lessonVersion } : {}),
    ...(input.lessonManifestUrl ? { manifestUrl: input.lessonManifestUrl } : {}),
    ...(input.lessonManifestSha256 ? { manifestSha256: input.lessonManifestSha256 } : {}),
    source: input.lesson.source,
  } : undefined;
  return {
    $schema: LESSON_DATA_LOCK_SCHEMA,
    schema: 1,
    kind: "biolang-lesson-data-lock",
    generatedAt: input.generatedAt ?? new Date().toISOString(),
    project: { notebook, script },
    ...(lesson ? { lesson } : {}),
    files: (input.lesson?.datasets ?? []).map(dataset => ({ ...dataset, path: dataset.path.replaceAll("\\", "/"), role: "input" as const })),
  };
}

function projectReadme(input: LessonProjectInput, lock: LessonDataLock) {
  const title = input.lesson?.title ?? (input.workspaceName.trim() || "BioLang notebook");
  const data = lock.files.length
    ? `This project declares ${lock.files.length} input file${lock.files.length === 1 ? "" : "s"}. Downloading is a separate, explicit action. BioLang verifies each declared byte count and SHA-256 digest before making a file available.\n\n\`\`\`console\nbl lesson prepare lesson-data.json\n\`\`\``
    : "This notebook declares no lesson-managed input files.";
  return `# ${title}\n\nThis is a reproducible handoff exported by BioLang Studio. It contains the original literate notebook and an executable BioLang script. Dataset bytes and credentials are not embedded.\n\n## Prepare data\n\n${data}\n\n## Run\n\nPrepare (or verify) the declared inputs and run the generated script from a clean interpreter:\n\n\`\`\`console\nbl lesson run lesson-data.json\n\`\`\`\n\nTo inspect or edit the narrative version instead:\n\n\`\`\`console\nbl notebook ${lock.project.notebook}\n\`\`\`\n\n## Files\n\n- \`${lock.project.notebook}\`: canonical Studio notebook\n- \`${lock.project.script}\`: executable code cells in notebook order\n- \`lesson-data.json\`: paths, sources, byte sizes, SHA-256 checksums, citations, and rights\n- \`PROVENANCE.md\`: human-readable source and data-use notes\n\nPreparation never executes notebook code. Existing files with different content are not trusted; BioLang replaces them only when you explicitly pass \`--force\`. Review each dataset's rights and source terms before use or redistribution.\n`;
}

function provenance(input: LessonProjectInput, lock: LessonDataLock) {
  const lines = [
    "# Provenance and rights",
    "",
    `Exported: ${lock.generatedAt}`,
    `Workspace: ${input.workspaceName}`,
  ];
  if (lock.lesson) {
    lines.push("", "## Lesson", "", `- ${lock.lesson.title} (\`${lock.lesson.id}\`)`, `- Source: ${lock.lesson.source.title} — ${lock.lesson.source.url}`, `- Note: ${lock.lesson.source.note}`);
    if (lock.lesson.version) lines.push(`- Registry version: ${lock.lesson.version}`);
    if (lock.lesson.manifestUrl) lines.push(`- Manifest: ${lock.lesson.manifestUrl}`);
    if (lock.lesson.manifestSha256) lines.push(`- Manifest SHA-256: \`${lock.lesson.manifestSha256}\``);
  }
  lines.push("", "## Inputs", "");
  if (!lock.files.length) lines.push("No lesson-managed inputs were declared.");
  for (const file of lock.files) {
    lines.push(`### ${file.title}`, "", `- Path: \`${file.path}\``, `- Source: ${file.source}`, `- URL: ${file.url}`, `- Citation: ${file.citation}`, `- Rights: ${file.rights}`, `- Size: ${file.bytes} bytes`, `- SHA-256: \`${file.sha256}\``, "");
  }
  lines.push("Dataset bytes are not part of this archive. The source's rights and terms continue to apply when a user prepares them.", "");
  return lines.join("\n");
}

export function buildLessonProject(input: LessonProjectInput) {
  const base = safeProjectBase(input.filename);
  const lock = lessonDataLock(input);
  const notebook = serializeNotebook(input.cells);
  const script = generatedBioLangScript(input.cells, lock.project.notebook);
  return {
    filename: `${base}-cli.zip`,
    lock,
    notebook,
    script,
    bytes: createZip([
      { name: lock.project.notebook, data: notebook },
      { name: lock.project.script, data: script },
      { name: "lesson-data.json", data: `${JSON.stringify(lock, null, 2)}\n` },
      { name: "README.md", data: projectReadme(input, lock) },
      { name: "PROVENANCE.md", data: provenance(input, lock) },
    ], new Date(lock.generatedAt)),
  };
}
